version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_management
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - order-network

  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: order-management-api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Postgres=Host=postgres;Database=order_management;Username=postgres;Password=postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - order-network

networks:
  order-network:
    driver: bridge

volumes:
  pgdata: